import = [ "~/.config/alacritty/themes/dracula.toml" ]

[env]
TERM = "alacritty"

[window]
decorations = "none"
opacity = 0.85
dynamic_title = true

[font]
size = 14

  [font.normal]
  family = "CaskaydiaCove Nerd Font"

[cursor.style]
shape = "Block"
blinking = "On"
