[general]
import = ["~/.config/alacritty/themes/dracula.toml"]

[window]
decorations = "None"
opacity = 0.85

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
size = 13

[cursor]
style = { shape = "Block", blinking = "On" }
